# Generated by Django 4.1.5 on 2023-01-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfamyli', '0002_alter_child_name_alter_parent_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='Team',
        ),
        migrations.RenameModel(
            old_name='Parent',
            new_name='Town',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='parent',
            new_name='town',
        ),
    ]
