# Generated by Django 4.1.5 on 2023-01-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfamyli', '0003_rename_child_team_rename_parent_town_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='town',
            new_name='parent',
        ),
    ]
